// src/App.jsx
import React from 'react';
import Navbar from './components/Navbar/index.jsx';
import HeroSection from './components/HeroSection/index.jsx';
import AboutSection from './components/AboutSection/index.jsx';
import SkillsSection from './components/SkillsSection/index.jsx';
import ProjectsSection from './components/ProjectsSection/index.jsx';
import ServicesSection from './components/ServicesSection/index.jsx';
import TimelineSection from './components/TimelineSection/index.jsx'; // Now acts as Experience
import TestimonialsSection from './components/TestimonialsSection/index.jsx';
import ContactSection from './components/ContactSection/index.jsx';
import Footer from './components/Footer/index.jsx';
import './App.css';

function App() {
  return (
    <div className="app-wrapper bg-section-white text-slate-800 min-h-screen font-sans selection:bg-teal-500 selection:text-white transition-colors duration-300">
      <Navbar />
      
      <main>
        <HeroSection />
        <AboutSection />
        <SkillsSection />
        <ProjectsSection />
        <ServicesSection />
        <TimelineSection />
        <TestimonialsSection />
        <ContactSection />
      </main>

      <Footer />
    </div>
  );
}

export default App;

// src/App.vue
<template>
  <div class="app-wrapper">
    <!-- Navbar Header -->
    <Navbar />

    <!-- Main Sections -->
    <main>
      <HeroSection />
      <AboutSection />
      <ServicesSection />
      <ProjectsSection />
      <CodeShowcase />
      <SkillsSection />
      <TimelineSection />
      <TestimonialsSection />
      <FaqSection />
      <ContactSection />
    </main>

    <!-- Footer -->
    <Footer />
  </div>
</template>

<script setup>
import Navbar from './components/Navbar.vue'
import HeroSection from './components/HeroSection.vue'
import AboutSection from './components/AboutSection.vue'
import ServicesSection from './components/ServicesSection.vue'
import ProjectsSection from './components/ProjectsSection.vue'
import CodeShowcase from './components/CodeShowcase.vue'
import SkillsSection from './components/SkillsSection.vue'
import TimelineSection from './components/TimelineSection.vue'
import TestimonialsSection from './components/TestimonialsSection.vue'
import FaqSection from './components/FaqSection.vue'
import ContactSection from './components/ContactSection.vue'
import Footer from './components/Footer.vue'
</script>

<style scoped>
.app-wrapper {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background-color: var(--bg-white);
  color: var(--text-dark);
  position: relative;
}

main {
  flex-grow: 1;
}
</style>
